### ISSUE TITLE
Login Bug?

### ISSUE THREAD

**Issue by br8th** [19peaches/vularai-spa#6]
Users are able to login provided a registered username and any password at all

**Comment by 19peaches** [comment]
Hmmmm .... yeah that's probably not good. My initial thought is that this is probably on the API side of things. 

Did you do any local debugging to see what's returned?

Keep in mind this is like super alpha so I don't expect for things to not be broken.

**Comment by 19peaches** [comment]
As I suspected. This was resolved in the latest commit on the API, please pull the latest and give that a shot.
